#!/bin/sh
set -e
package_name=deepin-installer-reborn-tweaks
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/deepin-installer-reborn"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/deepin-installer-reborn/resources/default_wallpaper.jpg"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/deepin-installer-reborn"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/deepin-installer-reborn/resources/default_wallpaper.jpg"
;;
esac
exit 0
